### ISSUE TITLE
Move Translation Propagation into a plugin

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#337]
Cross project translations matching was proposed in https://glotpress.trac.wordpress.org/ticket/327 and implemented via [1034](https://glotpress.trac.wordpress.org/changeset/1034), [1095](https://glotpress.trac.wordpress.org/changeset/1034), [1097](https://glotpress.trac.wordpress.org/changeset/1097), [1126](https://glotpress.trac.wordpress.org/changeset/1126), [1128](https://glotpress.trac.wordpress.org/changeset/1128),  [1144](https://glotpress.trac.wordpress.org/changeset/1144), [1176](https://glotpress.trac.wordpress.org/changeset/1176), [1177](https://glotpress.trac.wordpress.org/changeset/1177), and [1178](https://glotpress.trac.wordpress.org/changeset/1178).

It started as an alternative for the Translation Memory and isn't yet finalized – it probably shouldn't be included in v1.0 of the plugin at all.
Some of the recent commits are more or less tied to the workflow on translate.w.org which is usually a bad idea because GlotPress is used by a few more platforms.

Translations matching in its current state has a few issues:
- Wrong translations can be automatically validated, see https://meta.trac.wordpress.org/ticket/1411.
- There is no difference between nouns and verbs, see also https://wordpress.slack.com/archives/polyglots/p1457105584001087.
- It doesn't scale: On translate.w.org an import with enabled matching for one original for ~100 translation sets takes ~3 seconds. For 50 originals that would be 2,5 minutes. (#336 would help here.)
- On systems with more than one database the propagation can lead to duplicates. That's why it's currently [disabled](https://meta.trac.wordpress.org/changeset/2167) on translate.w.org.

I'm proposing to move Translation Propagation into a plugin which would still be maintained by us but can benefit of a separate release cycle. It should be marked as a feature plugin which would allow us to perform potential breaking changes.
This step would also be future-proof: When the real Translation Memory gets developed (which should probably start as a feature plugin as well) it's unlikely that both systems would run at the same time.

**ToDo:**
- [x] Remove the code from the plugin
- [x] Create the plugin
- [x] Publish it in the w.org repo

**Comment by toolstack** [comment]
I'm not sure this is really a bug, but I agree it should be moved out to a plugin, if possible.

I don't know if that's possible for 1.1 or not though.  Could we disable it for 1.1 and look to remove it in 1.2?  That way if an install is using it in 1.0 they could re-enable it with a define in 1.1.

**Comment by ocean90** [comment]
Plugin has its own repo: https://github.com/GlotPress/gp-translation-propagation

**Comment by ocean90** [comment]
Plugin submitted to the w.org repo on 2016-3-26.

**Comment by ocean90** [comment]
It's live: https://wordpress.org/plugins/gp-translation-propagation/
