### ISSUE TITLE
Tablesorter theme doesn't use same colors as before

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#544]
## Before:

<img width="572" alt="before" src="https://cloud.githubusercontent.com/assets/617637/18482636/3a7d7b2a-79e1-11e6-9c12-9c76d7ffadd6.png">
## After:

<img width="623" alt="after" src="https://cloud.githubusercontent.com/assets/617637/18482643/3f7b5a02-79e1-11e6-9cb6-fd9ee57ae118.png">
## ToDo:
- [x] Blue highlight color, but only when a colum sort was changed.
- [x] Background color of `.odd td` should be white.
- [x] The border between table cells should be restored.
- [x] There should be no [flickering](https://cloud.githubusercontent.com/assets/617637/18563699/fac1cd66-7b88-11e6-9f18-0220273c6599.gif) after Tablesorter has initialized the table.

**Comment by ocean90** [comment]
@toolstack Sorry, I wasn't clear enough. I've updated the description with a todo list.

**Comment by toolstack** [comment]
I would argue that "only when a column sort was changed" is a bug in the old code.  The current sort column  should be highlighted at all times.  I have to admit I didn't even notice you could sort by column until I was looking through the code one day and noticed the table sorter script :)

The background colour of the odd rows should probably not be white any more as the new table sorter code highlights the row that the cursor is over in white.  We could change that to another colour though or remove it of course, but it seems like a good feature overall.

I'll add the cell boards back in.

The flickering seems to be chrome specific, I'll see if I can track it down.

**Comment by toolstack** [comment]
Dug in to the chrome issue and it turns out the code doesn't support chrome (see [here](https://mottie.github.io/tablesorter/docs/#Compatibility)).

By manuall adding the various classes the flicker can be significantly reduced, but the columns still "bounce" (grow and then shrink back) once during table init... sometimes.  Other times it seems to be fine.

**Comment by toolstack** [comment]
Some more poking eliminates the table sorter from the last bit of the flickering.  It looks like Chrome has a bug in it's rendering engine that miscalculates the column width during the first pass and then "fixes" it on a second pass.

**Comment by toolstack** [comment]
Confirmed the "bounce" happens in previous versions of GP, so not related to the table sorter update.  

The only way it looks like to fix it is to set a fixed width for the table that is greater than the sum of the row requirements.  For example if you set the table width from `auto` to `600px` (note 600px is dependent on the locale list and display properties.  On my setup the table requires at minimum 536px to  display everything so any number above that would work).

Or setting it to `100%` works as well but of course looks strange with so few columns.

**Comment by ocean90** [comment]
> I would argue that "only when a column sort was changed" is a bug in the old code. The current sort column should be highlighted at all times.

The current blue is quite distracting, that's why I suggested to apply this only when a user changes it. I think we should remove the background and make the arrows more prominent instead. They should be white as a first step.

> The background colour of the odd rows should probably not be white any more as the new table sorter code highlights the row that the cursor is over in white.

OK, let's wait for the redesign…

> Dug in to the chrome issue and it turns out the code doesn't support chrome.

Well, the plugin is quite old, but nice that we support IE 6 at least. Maybe we should have searched for an alternative instead of updating it in #502.

**Comment by toolstack** [comment]
> The current blue is quite distracting, that's why I suggested to apply this only when a user changes it. I think we should remove the background and make the arrows more prominent instead. They should be white as a first step.

I agree with the white arrows, I'll update the css.  Let's change the highligh color to something less distracting.  We could go with a darker grey or (my preference) the GP purple.

> Well, the plugin is quite old, but nice that we support IE 6 at least. Maybe we should have searched for an alternative instead of updating it in #502.

I assumed we'd wait for the redesign on replacing the current table sorter, 502 grew out of the javascript fixes and minification work.

**Comment by toolstack** [comment]
Some sample options:

![sort-highlights](https://cloud.githubusercontent.com/assets/9053749/18609104/db91206e-7cc7-11e6-8c78-89538ab38872.png)

#0026FF Dark Blue
#000000 Black
#32373C GP Base Gray
#826EB4 GP Purple
#3399FF Light Blue

I think black actually makes the most sense, it's unobtrusive and it's the highlight we use for the top level menu as well.

**Comment by ocean90** [comment]
Thanks for graphic. Let's use 32373C.

**Comment by toolstack** [comment]
Done.
